name = "Sinograms"
uuid = "02a14def-c6e6-4ab0-b2df-0ab64bc8cdd7"
authors = ["fessler <fessler@umich.edu>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageGeoms = "9ee76f2b-840d-4475-b6d6-e485c9297852"
LazyGrids = "7031d0ef-c40d-4431-b2f8-61a8d2f650db"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
FFTW = "1.4.5"
ImageGeoms = "0.6"
LazyGrids = "0.4"
Requires = "1.3"
julia = "1.6"
